### PR TITLE
Upgraded PlantUML version

### PR DESCRIPTION
**Pull request by hekonsek**
Hi,

Love the project :) . Can we just try to upgrade PlantUML version really quick?

Cheers!

### CODE REVIEW

**Comment by nebbles** [comment]
Second this. I am getting warnings from running the current version. [The forum seems to suggest](https://forum.plantuml.net/10650/illegal-reflective-access-sourceforge-plantuml-svggraphics) this might be to do with the plantuml.jar itself.

<details>
<summary>Error I am getting</summary>
<pre>
<code>
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sourceforge.plantuml.svg.SvgGraphics (file:/plantuml.jar) to constructor com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl()
WARNING: Please consider reporting this to the maintainers of net.sourceforge.plantuml.svg.SvgGraphics
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
</code>
</pre>
</details>

**Comment by lindt** [comment]
I repaired the ./gather_tags script, so it now builds all versions automatically. Would be awesome if you could try it out to see if your version (is available as tag) or even a newer version works for you. thanks....and thanks for reminding me, that the script was outdated

**Comment by nebbles** [comment]
Sorted my problem out too (I just pulled the latest). Thank you!

**Comment by lindt** [comment]
thx. Updated to 1.2023.1.
sorry for haven't seeing your PR before.
Close it here, please reopen, if there are still issues.

**Pull request closed without merging**
